import moment from "moment";
import { v4 as uuidv4 } from "uuid";
export const data1 = [
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Manual Scheduled",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Retrieve Scheduled",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Import",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Push",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Export",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Manual Scheduled",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Retrieve Scheduled",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Import",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Push",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Export",
  },

  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Manual Scheduled",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Retrieve Scheduled",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Import",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Push",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Export",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Manual Scheduled",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Retrieve Scheduled",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Import",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Push",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Export",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Manual Scheduled",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Retrieve Scheduled",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Import",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Push",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Export",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Manual Scheduled",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Retrieve Scheduled",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Import",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Push",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Export",
  },
];

export const data2 = [
  {
    year: moment().subtract(0, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200),
    category: "Total",
  },
  {
    year: moment().subtract(0, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200),
    category: "Failed",
  },
  {
    year: moment().subtract(1, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300),
    category: "Total",
  },
  {
    year: moment().subtract(1, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300),
    category: "Failed",
  },
  {
    year: moment().subtract(2, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Total",
  },
  {
    year: moment().subtract(2, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed",
  },
  {
    year: moment().subtract(3, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 500),
    category: "Total",
  },
  {
    year: moment().subtract(3, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 500),
    category: "Failed",
  },
  {
    year: moment().subtract(4, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Total",
  },
  {
    year: moment().subtract(4, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed",
  },
  {
    year: moment().subtract(5, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Total",
  },
  {
    year: moment().subtract(5, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed",
  },
  {
    year: moment().subtract(6, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Total",
  },
  {
    year: moment().subtract(6, "minutes").format("hh:mm"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed",
  },
];

export const data3 = [
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed Job",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed Data",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed Supplier Conn",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed Auth",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Bad Req",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed Export",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 200),
    category: "Failed Job",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 200),
    category: "Failed Data",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 200),
    category: "Failed Supplier Conn",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 200),
    category: "Failed Auth",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 200),
    category: "Bad Req",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 200),
    category: "Failed Export",
  },

  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Failed Job",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Failed Data",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Failed Supplier Conn",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Failed Auth",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Bad Req",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Failed Export",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Failed Job",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Failed Data",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Failed Supplier Conn",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Failed Auth",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Bad Req",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Failed Export",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed Job",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed Data",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed Supplier Conn",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed Auth",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Bad Req",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed Export",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Failed Job",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Failed Data",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Failed Supplier Conn",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Failed Auth",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Bad Req",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Failed Export",
  },
];

export const ActiveJobs = [
  {
    action: "Retrieve",
    Name: "Shaheer",
    status: "Warning",
  },
  {
    action: "Import",
    Name: "Rehman",
    status: "Error",
  },
  {
    action: "Export",
    Name: "Asad",
    status: "OK",
  },
  {
    action: "Import",
    Name: "Danial",
    status: "In Progress",
  },
  {
    action: "Retrieve",
    Name: "Shaheer",
    status: "Warning",
  },
];

export const RecentAddedSuppliers = [
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "s001",
    Name: `BOOKER`,
    Schedule: "Enable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "s002",
    Name: `BESTWAY`,
    Schedule: "Disable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "s003",
    Name: `LONDIS`,
    Schedule: "Disable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "s004",
    Name: `NISA`,
    Schedule: "Disable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "s005",
    Name: `COSTCUTTER`,
    Schedule: "Disable",
  },
];

export const RecentAddedCustomers = [
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "c001",
    Name: `Customer 01`,
    Schedule: "Disable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "c002",
    Name: `Customer 02`,
    Schedule: "Enable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "c003",
    Name: `Customer 03`,
    Schedule: "Disable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "c004",
    Name: `Customer 04`,
    Schedule: "Disable",
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    ID: "c005",
    Name: `Customer 05`,
    Schedule: "Enable",
  },
];

export const FailedConnections = [
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Supplier: `Customer 01`,
    Customer: `BOOKER`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Supplier: `Customer 02`,
    Customer: `BESTWAY`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Supplier: `Customer 03`,
    Customer: `LONDIS`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Supplier: `Customer 04`,
    Customer: `NISA`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Supplier: `Customer 05`,
    Customer: `COSTCUTTER`,
  },
];

export const RecentAlarms = [
  {
    severity: `Severity 01`,
    type: `Failed Job`,
    description: `Description 01`,
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
  },
  {
    severity: `Severity 02`,
    type: `Failed Data Record`,
    description: `Description 02`,
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
  },
  {
    severity: `Severity 03`,
    type: `Failed Supplier`,
    description: `Description 03`,
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
  },
  {
    severity: `Severity 04`,
    type: `Failed Authentication`,
    description: `Description 04`,
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
  },
  {
    severity: `Severity 05`,
    type: `Bad Request`,
    description: `Description 05`,
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
  },
];

export const data4 = [
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Retreive",
    Status: `Warning`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Import",
    Status: `Error`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Export",
    Status: `OK`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Import",
    Status: `In-Progress`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Retreive",
    Status: `Error`,
  },
];

export const data5 = [
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Retreive",
    Status: `Warning`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Retreive",
    Status: `Error`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Export",
    Status: `OK`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Import",
    Status: `Error`,
  },
  {
    Time: moment().format("MM/DD - hh:mm:ss"),
    key: uuidv4(),
    Action: "Import",
    Status: `In-Progress`,
  },
];

export const data6 = [
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Total",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed",
  },
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400),
    category: "Failed",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Failed",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Total",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Failed",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 200),
    category: "Failed",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Total",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Failed",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 300 + 400),
    category: "Failed",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Total",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Failed",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Total",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Failed",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 400 + 200),
    category: "Total",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Total",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 500),
    category: "Failed",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Total",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Total",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Total",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: Math.floor(Math.random() * 200 + 300),
    category: "Failed",
  },
];

export const data7 = [
  {
    year: moment().subtract(0, "days").format("DD/MM"),
    key: uuidv4(),
    value: 50,
    category: "Total",
  },
  {
    year: moment().subtract(1, "days").format("DD/MM"),
    key: uuidv4(),
    value: 40,
    category: "Total",
  },
  {
    year: moment().subtract(2, "days").format("DD/MM"),
    key: uuidv4(),
    value: 30,
    category: "Total",
  },
  {
    year: moment().subtract(3, "days").format("DD/MM"),
    key: uuidv4(),
    value: 20,
    category: "Total",
  },
  {
    year: moment().subtract(4, "days").format("DD/MM"),
    key: uuidv4(),
    value: 25,
    category: "Total",
  },
  {
    year: moment().subtract(5, "days").format("DD/MM"),
    key: uuidv4(),
    value: 45,
    category: "Total",
  },
];

export const jobListing = [
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
  {
    "Customer Name": "Syed Ebad",
    Status: "Completed",
    "Start Time": moment().format("HH-MM-SS"),
    "End Start": moment().format("HH-MM-SS"),
    "Job Type": "Export",
    "Job Trigger": "Manual",
    key: uuidv4(),
  },
];
